config:
   ci: 'BITRISE'
   url: http://codestats.wolox.com.ar/
   token: <%= ENV[‘CODE_STATS_TOKEN’] %>
metrics:
   slather:
     name: 'Code Coverage'
     enabled: true
     minimum: 70
     upload_report: true
